### ISSUE TITLE
DEPRECATION: ComputedProperty.cacheable() is deprecated since Ember 1.10.0

### ISSUE THREAD

**Issue by avdv** [zendesk/ember-resource#101]
Hi.

Since Ember 1.10.0 using the `.cacheable()` call of computed properties is deprecated and results in a warning in the browser console:

```
DEPRECATION: ComputedProperty.cacheable() is deprecated. All computed properties are cacheable by default.
        at Descriptor.ComputedPropertyPrototype.cacheable (http://192.168.10.200:4200/static-assets/vendor.js:19577:11)
        at Ember.Resource.AbstractSchemaItem.Ember.Object.extend.property (http://192.168.10.200:4200/static-assets/vendor.js:80698:62)
        at createSchemaProperties (http://192.168.10.200:4200/static-assets/vendor.js:81527:57)
        at Function.Ember.Resource.reopenClass.define (http://192.168.10.200:4200/static-assets/vendor.js:81635:31)
        at http://192.168.10.200:4200/static-assets/adam.js:2023:34
        at mod.state (http://192.168.10.200:4200/static-assets/vendor.js:150:29)
        at tryFinally (http://192.168.10.200:4200/static-assets/vendor.js:30:14)
        at requireModule (http://192.168.10.200:4200/static-assets/vendor.js:148:5)
        at requireFrom (http://192.168.10.200:4200/static-assets/vendor.js:121:12)
```

As the warning says, cacheable is the default setting. That's the case since Ember 1.0.0, see https://github.com/emberjs/ember.js/commit/5ef55f22c584abc788fd98994af591f010ba82e9

I could create a pull request removing those calls if that is OK for you. Or, do you want to support Ember < 1.0 for any time longer?

**Comment by shajith** [comment]
Sorry about the delay in responding! 

+1 for removing `cacheable`, we are okay with not supporting < 1.0.
